### ISSUE TITLE
Add FinOps and Security Categories

### ISSUE THREAD

**Issue by agardnerIT** [keptn-contrib/artifacthub#169]
This issue proposes adding two new categories to the Keptn integrations page:

- FinOps
- Security

These categories would need to be added here: https://github.com/artifacthub/hub/blob/master/docs/keptn_annotations.md

**Comment by agardnerIT** [comment]
@Omkar0014 can you take this one too since you're working on https://github.com/keptn/keptn.github.io/issues/1420 which is related.

**Comment by Omkar0114** [comment]
Ya sure. Are these 2 issues are same?

**Comment by Omkar0114** [comment]
Hey, @agardnerIT I made PR for this.
https://github.com/artifacthub/hub/pull/2277

**Comment by agardnerIT** [comment]
Closing as PR is merged.
