### ISSUE TITLE
Come up with a way to share webhook based integrations

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/artifacthub#42]
Our very first webhook-service based integration was merged recently and is available here:

https://github.com/keptn-sandbox/artifacthub/tree/main/slack/0.1.0

# This raises several questions

## 1 How can we mark/specify that an integration is based on webhook-service (rather than something that needs to be installed with Keptn)?

Before we discuss this, yes this makes a difference. You can install such an integration without having access to a Kubernetes cluster, while things like argo-service or dynatrace-service require you to have full access to the Kubernetes cluster.

I vote for having the possibility of tagging such integrations, e.g., 
```
  keptn/kind: "webhook"
```

This can obviously be extended based on the use-case, e.g.

```
  keptn/kind: "notification,webhook"
```

## 2 How to define a simple but effective versioning scheme for such integrations?

E.g., why is the slack integration released with version 0.1.0? Why is it not 0.0.1 or 1.0.0? 

## 3 How to (automatically) verify that such an integration works with a certain Keptn version?

Right now the provided documentation for webhook with Slack works with Keptn 0.10.0 and the current Slack API. This information will be outdated at some point... How can we make sure that this information gets updated and verified for the next Keptn release?

**Comment by robertjahn** [comment]
Yes - I agree with something like this.  I had opened this enhancement too that could be driven by category meta-data https://github.com/keptn/keptn.github.io/issues/1036

**Comment by christian-kreuzberger-dtx** [comment]
for now, we can use existing webhook based integrations as templates. Closing this issue.
