### ISSUE TITLE
Promote to keptn-contrib

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/artifacthub#54]
Hi,

I propose to promote this repository to keptn-contrib.

According to https://github.com/keptn-sandbox/contributing/blob/master/CONTRIBUTING.md#how-to-be-promoted-to-keptn-contrib-organization the following criteria need to be fullfilled:

- [x] Automated builds - **this is not an integration, but a index repo - it's automatically deployed to [ArtifactHub](https://artifacthub.io/packages/search?org=keptn&sort=relevance&page=1)
- [x] Automated tests - **this index repo has a linter that checks if the yml files are correct: https://github.com/keptn-sandbox/artifacthub/blob/main/.github/workflows/ah_lint.yml **
- [ ] At least one release of the service compatible with the latest Keptn version - **does not apply**
- [x] At least one sponsor of the Keptn core team for your contribution (that would be myself @christian-kreuzberger-dtx )

Looking at [CODEOWNERS](https://github.com/keptn-sandbox/artifacthub/blob/main/CODEOWNERS), I would like to ask
- @TannerGilbert 
- @oleg-nenashev 

for their permission to move this repo from keptn-sandbox to keptn-contrib.

**Comment by oleg-nenashev** [comment]
Should it be actually a part of https://github.com/keptn ? While it lists integrations, it seems to be a core part of the project infrastructure.  I'm +1 for the promotion anyway

**Comment by christian-kreuzberger-dtx** [comment]
> Should it be actually a part of https://github.com/keptn ? While it lists integrations, it seems to be a core part of the project infrastructure. I'm +1 for the promotion anyway

Gould point. I would also see it best suited in github.com/keptn/artifacthub, but I am also not unhappy with keptn-contrib.

@AloisReitbauer @johannes-b @agrimmer  @thisthat any objections / counter proposals? (Please note: just having the repo in a certain GH organization doesn't mean that Keptn Core needs to maintain it).

**Comment by TannerGilbert** [comment]
Sorry for the late reply. I also support the promotion of this repository, and I also like the proposal to promote it directly to https://github.com/keptn, but this is in the hands of the Keptn Core team.

**Comment by oleg-nenashev** [comment]
I added it to the agenda of the next Kept meeting on Jan 13: https://docs.google.com/document/d/1y7a6uaN8fwFJ7IRnvtxSfgz-OGFq6u7bKN6F7NDxKPg/edit#heading=h.qrnua3yqlc1n

**Comment by christian-kreuzberger-dtx** [comment]
Promoted to keptn-contrib.
